# Generated by Django 6.0.6 on 2026-07-05 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_order_delivery_contact_phone_and_more'),
        ('restaurants', '0002_restaurant_account_name_restaurant_account_number_and_more'),
        ('users', '0003_conversationstate_business_ordering_as_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='send_orders_to_deli_dash',
            field=models.BooleanField(default=False, help_text='Use Deli Dash to manually buy from this restaurant instead of messaging the restaurant directly.'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.CreateModel(
            name='MenuItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to='users.customer')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_item_reviews', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
