# Generated by Django 6.0.6 on 2026-07-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_menuitem_inventory_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.DeleteModel(
            name='RestaurantImage',
        ),
    ]
