# Generated by Django 6.0.6 on 2026-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitem_rating_menuitem_total_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='estimated_prep_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Estimated kitchen preparation time shown to customers and operators.'),
        ),
    ]
