ASK_LOCATION = "ASK_LOCATION"
ASK_NAME = "ASK_NAME"
ASK_ROLE = "ASK_ROLE"
CHECKOUT_ASK_NAME = "CHECKOUT_ASK_NAME"

HOME = "HOME"

BROWSE_RESTAURANTS = "BROWSE_RESTAURANTS"

SEARCH_RESTAURANTS = "SEARCH_RESTAURANTS"

TYPE_ORDER = "TYPE_ORDER"

CONFIRM_TYPED_ORDER = "CONFIRM_TYPED_ORDER"

SEARCH_RESULTS = "SEARCH_RESULTS"

VIEW_RESTAURANT = "VIEW_RESTAURANT"

VIEW_MENU = "VIEW_MENU"

VIEW_ITEM = "VIEW_ITEM"

VIEW_CART = "VIEW_CART"

CHECKOUT = "CHECKOUT"

SELECT_DELIVERY_RIDER = "SELECT_DELIVERY_RIDER"

PAYMENT = "PAYMENT"

ORDER_STATUS = "ORDER_STATUS"

TRACK_ORDER = "TRACK_ORDER"

CHANGE_LOCATION = "CHANGE_LOCATION"

RATE_ORDER = "RATE_ORDER"

REVIEW_CHOICE = "REVIEW_CHOICE"

REGISTER_RESTAURANT = "REGISTER_RESTAURANT"

REGISTER_RIDER = "REGISTER_RIDER"

BUSINESS_HOME = "BUSINESS_HOME"

RESTAURANT_ADMIN = "RESTAURANT_ADMIN"

RIDER_ADMIN = "RIDER_ADMIN"

CONFIRM_DELIVERY_DETAILS = "CONFIRM_DELIVERY_DETAILS"

DELISEND_CONFIRMATION = "DELISEND_CONFIRMATION"

HELP = "HELP"

STEP_CHOICES = [
    (ASK_LOCATION, "Ask Location"),
    (ASK_NAME, "Ask Name"),
    (ASK_ROLE, "Ask Role"),
    (CHECKOUT_ASK_NAME, "Checkout Ask Name"),
    (HOME, "Home"),
    (BROWSE_RESTAURANTS, "Browse Restaurants"),
    (SEARCH_RESTAURANTS, "Search Restaurants"),
    (TYPE_ORDER, "Type Order"),
    (CONFIRM_TYPED_ORDER, "Confirm Typed Order"),
    (SEARCH_RESULTS, "Search Results"),
    (VIEW_RESTAURANT, "View Restaurant"),
    (VIEW_MENU, "View Menu"),
    (VIEW_ITEM, "View Item"),
    (VIEW_CART, "View Cart"),
    (CHECKOUT, "Checkout"),
    (SELECT_DELIVERY_RIDER, "Select Delivery Rider"),
    (PAYMENT, "Payment"),
    (ORDER_STATUS, "Order Status"),
    (TRACK_ORDER, "Track Order"),
    (CHANGE_LOCATION, "Change Location"),
    (RATE_ORDER, "Rate Order"),
    (REVIEW_CHOICE, "Review Choice"),
    (REGISTER_RESTAURANT, "Register Restaurant"),
    (REGISTER_RIDER, "Register Rider"),
    (BUSINESS_HOME, "Business Home"),
    (RESTAURANT_ADMIN, "Restaurant Admin"),
    (RIDER_ADMIN, "Rider Admin"),
    (CONFIRM_DELIVERY_DETAILS, "Confirm Delivery Details"),
    (DELISEND_CONFIRMATION, "Deli Dash Confirmation"),
    (HELP, "Help"),
]
