# Generated by Django 6.0.6 on 2026-07-04 15:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryrider'),
        ),
        migrations.AddField(
            model_name='order',
            name='fallback_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('1800.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='fallback_status',
            field=models.CharField(choices=[('NOT_NEEDED', 'Not needed'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='NOT_NEEDED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_asked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_availability_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASKED', 'Asked'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TIMEOUT', 'Timed out')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_asked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_availability_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASKED', 'Asked'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TIMEOUT', 'Timed out')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.customer'),
        ),
    ]
