# Generated by Django 6.0.6 on 2026-07-06 09:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_order_delivery_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=12),
        ),
    ]
