# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_customer_service_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_delivery_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_delivery_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurant_dispatch_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
