# Generated by Django 6.0.6 on 2026-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_state_options_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='formatted_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
