# Generated by Django 6.0.6 on 2026-07-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_address_formatted_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
