# Generated by Django 6.0.6 on 2026-07-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_order_delivery_contact_phone_and_more'),
        ('payments', '0002_nombawebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('RIDER', 'Delivery Rider')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('expected_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('merchant_reference', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LOOKED_UP', 'Account Looked Up'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'recipient_type')},
            },
        ),
    ]
