"""
Django settings for deli project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from decimal import Decimal

from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "rest_framework",

    "users",
    "restaurants",
    "cart",
    "orders",
    "payments",
    "delivery",
    "whatsapp",
    "notifications",
    "ai",
    "analytics",
    "locations",
    "django_filters",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'deli.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'deli.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

PUBLIC_BASE_URL = os.getenv(
    "PUBLIC_BASE_URL",
    os.getenv("NGROK_URL", ""),
).rstrip("/")

DELI_DASH_WHATSAPP_NUMBER = os.getenv(
    "DELI_DASH_WHATSAPP_NUMBER",
    "",
)

WHATSAPP_PUBLIC_NUMBER = os.getenv(
    "WHATSAPP_PUBLIC_NUMBER",
    "",
)

DELI_CUSTOMER_SERVICE_FEE = Decimal(
    os.getenv("DELI_CUSTOMER_SERVICE_FEE", "200")
)

DELI_MAINTENANCE_FEE = Decimal(
    os.getenv("DELI_MAINTENANCE_FEE", "100")
)

DELI_RESTAURANT_PAYOUT_FEE = Decimal(
    os.getenv("DELI_RESTAURANT_PAYOUT_FEE", "200")
)

DELI_RIDER_PAYOUT_FEE = Decimal(
    os.getenv("DELI_RIDER_PAYOUT_FEE", "200")
)

WHATSAPP_STALE_MESSAGE_MINUTES = int(
    os.getenv("WHATSAPP_STALE_MESSAGE_MINUTES", "20")
)

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": [

        "rest_framework.authentication.SessionAuthentication",

    ],

    "DEFAULT_PERMISSION_CLASSES": [

        "rest_framework.permissions.AllowAny",

    ],
    "DEFAULT_FILTER_BACKENDS":[

        "django_filters.rest_framework.DjangoFilterBackend"

    ],

}

NOMBA_BASE_URL = os.getenv(
    "NOMBA_BASE_URL",
    "https://sandbox.nomba.com/v1",
)

NOMBA_ACCOUNT_ID = (
    os.getenv("NOMBA_ACCOUNT_ID")
    or os.getenv("NOMBA_PARENT_ACCOUNT_ID")
)

NOMBA_SUB_ACCOUNT_ID = os.getenv("NOMBA_SUB_ACCOUNT_ID", "")

NOMBA_CLIENT_ID = os.getenv("NOMBA_CLIENT_ID")

NOMBA_CLIENT_SECRET = os.getenv("NOMBA_CLIENT_SECRET")

NOMBA_WEBHOOK_SECRET = os.getenv("NOMBA_WEBHOOK_SECRET")

NOMBA_CALLBACK_URL = os.getenv("NOMBA_CALLBACK_URL")

NOMBA_ALLOWED_PAYMENT_METHODS = [
    method.strip()
    for method in os.getenv(
        "NOMBA_ALLOWED_PAYMENT_METHODS",
        "",
    ).split(",")
    if method.strip()
]
