# Generated by Django 6.0.6 on 2026-07-04 07:12

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('ASK_LOCATION', 'Ask Location'), ('ASK_NAME', 'Ask Name'), ('HOME', 'Home'), ('BROWSE_RESTAURANTS', 'Browse Restaurants'), ('SEARCH_RESTAURANTS', 'Search Restaurants'), ('SEARCH_RESULTS', 'Search Results'), ('VIEW_RESTAURANT', 'View Restaurant'), ('VIEW_MENU', 'View Menu'), ('VIEW_ITEM', 'View Item'), ('VIEW_CART', 'View Cart'), ('CHECKOUT', 'Checkout'), ('PAYMENT', 'Payment'), ('ORDER_STATUS', 'Order Status'), ('TRACK_ORDER', 'Track Order'), ('CHANGE_LOCATION', 'Change Location'), ('RATE_ORDER', 'Rate Order'), ('HELP', 'Help')], default='ASK_NAME', max_length=50)),
                ('search_query', models.CharField(blank=True, default='', max_length=255)),
                ('search_result_type', models.JSONField(blank=True, default=list, max_length=20)),
                ('search_result_ids', models.JSONField(blank=True, default=list)),
                ('restaurant_ids', models.JSONField(blank=True, default=list)),
                ('last_message', models.TextField(blank=True)),
                ('navigation_stack', models.JSONField(blank=True, default=users.models.default_navigation_stack)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.area')),
                ('selected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurants.category')),
                ('selected_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('selected_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurants.menuitem')),
                ('selected_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurants.restaurant')),
                ('selected_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.state')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='users.customer')),
            ],
        ),
    ]
