# Generated by Django 6.0.6 on 2026-07-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationstate',
            name='search_area',
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='search_city',
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='search_state',
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='selected_restaurant',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='last_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.area'),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city'),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.state'),
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='current_step',
            field=models.CharField(choices=[('ASK_LOCATION', 'Ask Location'), ('ASK_NAME', 'Ask Name'), ('HOME', 'Home'), ('BROWSE_RESTAURANTS', 'Browse Restaurants'), ('SEARCH_RESTAURANTS', 'Search Restaurants'), ('SEARCH_RESULTS', 'Search Results'), ('VIEW_RESTAURANT', 'View Restaurant'), ('VIEW_MENU', 'View Menu'), ('VIEW_ITEM', 'View Item'), ('VIEW_CART', 'View Cart'), ('CHECKOUT', 'Checkout'), ('PAYMENT', 'Payment'), ('ORDER_STATUS', 'Order Status'), ('TRACK_ORDER', 'Track Order'), ('CHANGE_LOCATION', 'Change Location'), ('RATE_ORDER', 'Rate Order'), ('HELP', 'Help')], default='ASK_NAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='locations.area'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='formatted_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
