# Generated by Django 6.0.6 on 2026-07-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0002_order_delivery_address_order_delivery_contact_phone_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='delivery_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='delivery_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_delivery_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.deliveryrider'),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='current_step',
            field=models.CharField(choices=[('ASK_LOCATION', 'Ask Location'), ('ASK_NAME', 'Ask Name'), ('HOME', 'Home'), ('BROWSE_RESTAURANTS', 'Browse Restaurants'), ('SEARCH_RESTAURANTS', 'Search Restaurants'), ('SEARCH_RESULTS', 'Search Results'), ('VIEW_RESTAURANT', 'View Restaurant'), ('VIEW_MENU', 'View Menu'), ('VIEW_ITEM', 'View Item'), ('VIEW_CART', 'View Cart'), ('CHECKOUT', 'Checkout'), ('SELECT_DELIVERY_RIDER', 'Select Delivery Rider'), ('PAYMENT', 'Payment'), ('ORDER_STATUS', 'Order Status'), ('TRACK_ORDER', 'Track Order'), ('CHANGE_LOCATION', 'Change Location'), ('RATE_ORDER', 'Rate Order'), ('REGISTER_RESTAURANT', 'Register Restaurant'), ('REGISTER_RIDER', 'Register Rider'), ('DELISEND_CONFIRMATION', 'DeliSend Confirmation'), ('HELP', 'Help')], default='ASK_NAME', max_length=50),
        ),
    ]
