# Generated by Django 6.0.6 on 2026-07-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_conversationstate_search_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='formatted_address',
        ),
    ]
