# Generated by Django 6.0.6 on 2026-07-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_conversationstate_business_ordering_as_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='current_step',
            field=models.CharField(choices=[('ASK_LOCATION', 'Ask Location'), ('ASK_NAME', 'Ask Name'), ('ASK_ROLE', 'Ask Role'), ('CHECKOUT_ASK_NAME', 'Checkout Ask Name'), ('HOME', 'Home'), ('BROWSE_RESTAURANTS', 'Browse Restaurants'), ('SEARCH_RESTAURANTS', 'Search Restaurants'), ('TYPE_ORDER', 'Type Order'), ('CONFIRM_TYPED_ORDER', 'Confirm Typed Order'), ('SEARCH_RESULTS', 'Search Results'), ('VIEW_RESTAURANT', 'View Restaurant'), ('VIEW_MENU', 'View Menu'), ('VIEW_ITEM', 'View Item'), ('VIEW_CART', 'View Cart'), ('CHECKOUT', 'Checkout'), ('SELECT_DELIVERY_RIDER', 'Select Delivery Rider'), ('PAYMENT', 'Payment'), ('ORDER_STATUS', 'Order Status'), ('TRACK_ORDER', 'Track Order'), ('CHANGE_LOCATION', 'Change Location'), ('RATE_ORDER', 'Rate Order'), ('REVIEW_CHOICE', 'Review Choice'), ('REGISTER_RESTAURANT', 'Register Restaurant'), ('REGISTER_RIDER', 'Register Rider'), ('BUSINESS_HOME', 'Business Home'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('RIDER_ADMIN', 'Rider Admin'), ('CONFIRM_DELIVERY_DETAILS', 'Confirm Delivery Details'), ('DELISEND_CONFIRMATION', 'Deli Dash Confirmation'), ('HELP', 'Help')], default='ASK_NAME', max_length=50),
        ),
    ]
