# Generated by Django 6.0.6 on 2026-07-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_category_image_delete_restaurantimage'),
        ('users', '0003_remove_customer_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='search_query',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurants.category'),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurants.menuitem'),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='selected_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurants.restaurant'),
        ),
    ]
