# Generated by Django 6.0.6 on 2026-07-03 03:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_conversationstate_search_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='navigation_stack',
            field=models.JSONField(blank=True, default=users.models.default_navigation_stack),
        ),
    ]
