# Generated by Django 6.0.6 on 2026-07-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_conversationstate_navigation_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='restaurant_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='search_result_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='search_result_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
