# Generated by Django 6.0.6 on 2026-07-04 15:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
                ('vehicle_type', models.CharField(blank=True, default='Bike', max_length=80)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_code', models.CharField(blank=True, default='', max_length=20)),
                ('account_number', models.CharField(blank=True, default='', max_length=20)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_riders', to='locations.area')),
            ],
            options={
                'ordering': ['-rating', 'base_fee', 'name'],
            },
        ),
    ]
